<?php
/**
 * Metadata
 *
 * PHP version 5
 *
 * @category Class
 * @package  Deegitalbe\LaravelTrustupIoStorecove
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Deegitalbe\LaravelTrustupIoStorecove\Model;

use \ArrayAccess;
use \Deegitalbe\LaravelTrustupIoStorecove\ObjectSerializer;

/**
 * Metadata Class Doc Comment
 *
 * @category Class
 * @description Metadata about the document, used in the UI and reporting.
 * @package  Deegitalbe\LaravelTrustupIoStorecove
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Metadata implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Metadata';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'document_number' => 'string',
        'document_date' => 'string',
        'receiver_name' => 'string',
        'receiver_country' => 'string',
        'payload_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'document_number' => null,
        'document_date' => null,
        'receiver_name' => null,
        'receiver_country' => null,
        'payload_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_number' => 'documentNumber',
        'document_date' => 'documentDate',
        'receiver_name' => 'receiverName',
        'receiver_country' => 'receiverCountry',
        'payload_type' => 'payloadType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_number' => 'setDocumentNumber',
        'document_date' => 'setDocumentDate',
        'receiver_name' => 'setReceiverName',
        'receiver_country' => 'setReceiverCountry',
        'payload_type' => 'setPayloadType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_number' => 'getDocumentNumber',
        'document_date' => 'getDocumentDate',
        'receiver_name' => 'getReceiverName',
        'receiver_country' => 'getReceiverCountry',
        'payload_type' => 'getPayloadType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PAYLOAD_TYPE_INVOICE = 'Invoice';
    const PAYLOAD_TYPE_CREDIT_NOTE = 'CreditNote';
    const PAYLOAD_TYPE_INVOICE_RESPONSE = 'InvoiceResponse';
    const PAYLOAD_TYPE_ORDER = 'Order';
    const PAYLOAD_TYPE_ORDER_RESPONSE = 'OrderResponse';
    const PAYLOAD_TYPE_DESPATCH_ADVICE = 'DespatchAdvice';
    const PAYLOAD_TYPE_ORDER_BALANCE = 'OrderBalance';
    const PAYLOAD_TYPE_ORDER_CHANGE = 'OrderChange';
    const PAYLOAD_TYPE_ORDER_CANCELLATION = 'OrderCancellation';
    const PAYLOAD_TYPE_OTHER = 'Other';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPayloadTypeAllowableValues()
    {
        return [
            self::PAYLOAD_TYPE_INVOICE,
            self::PAYLOAD_TYPE_CREDIT_NOTE,
            self::PAYLOAD_TYPE_INVOICE_RESPONSE,
            self::PAYLOAD_TYPE_ORDER,
            self::PAYLOAD_TYPE_ORDER_RESPONSE,
            self::PAYLOAD_TYPE_DESPATCH_ADVICE,
            self::PAYLOAD_TYPE_ORDER_BALANCE,
            self::PAYLOAD_TYPE_ORDER_CHANGE,
            self::PAYLOAD_TYPE_ORDER_CANCELLATION,
            self::PAYLOAD_TYPE_OTHER,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['document_number'] = isset($data['document_number']) ? $data['document_number'] : null;
        $this->container['document_date'] = isset($data['document_date']) ? $data['document_date'] : null;
        $this->container['receiver_name'] = isset($data['receiver_name']) ? $data['receiver_name'] : null;
        $this->container['receiver_country'] = isset($data['receiver_country']) ? $data['receiver_country'] : null;
        $this->container['payload_type'] = isset($data['payload_type']) ? $data['payload_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['document_number'] === null) {
            $invalidProperties[] = "'document_number' can't be null";
        }
        if ($this->container['document_date'] === null) {
            $invalidProperties[] = "'document_date' can't be null";
        }
        if (!preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", $this->container['document_date'])) {
            $invalidProperties[] = "invalid value for 'document_date', must be conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.";
        }

        if ($this->container['receiver_name'] === null) {
            $invalidProperties[] = "'receiver_name' can't be null";
        }
        if ((mb_strlen($this->container['receiver_name']) > 128)) {
            $invalidProperties[] = "invalid value for 'receiver_name', the character length must be smaller than or equal to 128.";
        }

        if ((mb_strlen($this->container['receiver_name']) < 2)) {
            $invalidProperties[] = "invalid value for 'receiver_name', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['receiver_country'] === null) {
            $invalidProperties[] = "'receiver_country' can't be null";
        }
        if (!preg_match("/^[A-Z0-9]{2}$/", $this->container['receiver_country'])) {
            $invalidProperties[] = "invalid value for 'receiver_country', must be conform to the pattern /^[A-Z0-9]{2}$/.";
        }

        if ($this->container['payload_type'] === null) {
            $invalidProperties[] = "'payload_type' can't be null";
        }
        $allowedValues = $this->getPayloadTypeAllowableValues();
        if (!is_null($this->container['payload_type']) && !in_array($this->container['payload_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'payload_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_number
     *
     * @return string
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     *
     * @param string $document_number The number of the document. For UBL documents, this is the Invoice/ID or CreditNote/ID.
     *
     * @return $this
     */
    public function setDocumentNumber($document_number)
    {
        $this->container['document_number'] = $document_number;

        return $this;
    }

    /**
     * Gets document_date
     *
     * @return string
     */
    public function getDocumentDate()
    {
        return $this->container['document_date'];
    }

    /**
     * Sets document_date
     *
     * @param string $document_date The date of the document. For UBL documents, this is the Invoice/IssueDate or CreditNote/IssueDate.
     *
     * @return $this
     */
    public function setDocumentDate($document_date)
    {

        if ((!preg_match("/^\\d{4}-\\d{2}-\\d{2}$/", $document_date))) {
            throw new \InvalidArgumentException("invalid value for $document_date when calling Metadata., must conform to the pattern /^\\d{4}-\\d{2}-\\d{2}$/.");
        }

        $this->container['document_date'] = $document_date;

        return $this;
    }

    /**
     * Gets receiver_name
     *
     * @return string
     */
    public function getReceiverName()
    {
        return $this->container['receiver_name'];
    }

    /**
     * Sets receiver_name
     *
     * @param string $receiver_name The name of the receiver of the document. For UBL documents, this is the Invoice/AccountingCustomerParty/PartyName/Name or CreditNote/AccountingCustomerParty/PartyName/Name.
     *
     * @return $this
     */
    public function setReceiverName($receiver_name)
    {
        if ((mb_strlen($receiver_name) > 128)) {
            throw new \InvalidArgumentException('invalid length for $receiver_name when calling Metadata., must be smaller than or equal to 128.');
        }
        if ((mb_strlen($receiver_name) < 2)) {
            throw new \InvalidArgumentException('invalid length for $receiver_name when calling Metadata., must be bigger than or equal to 2.');
        }

        $this->container['receiver_name'] = $receiver_name;

        return $this;
    }

    /**
     * Gets receiver_country
     *
     * @return string
     */
    public function getReceiverCountry()
    {
        return $this->container['receiver_country'];
    }

    /**
     * Sets receiver_country
     *
     * @param string $receiver_country The country of the receiver of the document in ISO 3166-1 Alpha-2 format. For UBL documents, this is the Invoice/AccountingCustomerParty/PostalAddress/Country/IdentificationCode or CreditNote/AccountingCustomerParty/PostalAddress/Country/IdentificationCode.
     *
     * @return $this
     */
    public function setReceiverCountry($receiver_country)
    {

        if ((!preg_match("/^[A-Z0-9]{2}$/", $receiver_country))) {
            throw new \InvalidArgumentException("invalid value for $receiver_country when calling Metadata., must conform to the pattern /^[A-Z0-9]{2}$/.");
        }

        $this->container['receiver_country'] = $receiver_country;

        return $this;
    }

    /**
     * Gets payload_type
     *
     * @return string
     */
    public function getPayloadType()
    {
        return $this->container['payload_type'];
    }

    /**
     * Sets payload_type
     *
     * @param string $payload_type The type of payload.
     *
     * @return $this
     */
    public function setPayloadType($payload_type)
    {
        $allowedValues = $this->getPayloadTypeAllowableValues();
        if (!in_array($payload_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'payload_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payload_type'] = $payload_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


