<?php
/**
 * RawDocumentData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Deegitalbe\LaravelTrustupIoStorecove
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Deegitalbe\LaravelTrustupIoStorecove\Model;

use \ArrayAccess;
use \Deegitalbe\LaravelTrustupIoStorecove\ObjectSerializer;

/**
 * RawDocumentData Class Doc Comment
 *
 * @category Class
 * @description A document to send, in base64 encoded format.
 * @package  Deegitalbe\LaravelTrustupIoStorecove
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RawDocumentData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RawDocumentData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'parse' => 'bool',
        'parse_strategy' => 'string',
        'document' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'parse' => null,
        'parse_strategy' => null,
        'document' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parse' => 'parse',
        'parse_strategy' => 'parseStrategy',
        'document' => 'document'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parse' => 'setParse',
        'parse_strategy' => 'setParseStrategy',
        'document' => 'setDocument'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parse' => 'getParse',
        'parse_strategy' => 'getParseStrategy',
        'document' => 'getDocument'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const PARSE_STRATEGY_UBL = 'ubl';
    const PARSE_STRATEGY_CII = 'cii';
    const PARSE_STRATEGY_IDOC = 'idoc';
    const PARSE_STRATEGY_SETU14 = 'setu14';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getParseStrategyAllowableValues()
    {
        return [
            self::PARSE_STRATEGY_UBL,
            self::PARSE_STRATEGY_CII,
            self::PARSE_STRATEGY_IDOC,
            self::PARSE_STRATEGY_SETU14,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['parse'] = isset($data['parse']) ? $data['parse'] : true;
        $this->container['parse_strategy'] = isset($data['parse_strategy']) ? $data['parse_strategy'] : null;
        $this->container['document'] = isset($data['document']) ? $data['document'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getParseStrategyAllowableValues();
        if (!is_null($this->container['parse_strategy']) && !in_array($this->container['parse_strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'parse_strategy', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['document'] === null) {
            $invalidProperties[] = "'document' can't be null";
        }
        if ((mb_strlen($this->container['document']) < 5)) {
            $invalidProperties[] = "invalid value for 'document', the character length must be bigger than or equal to 5.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parse
     *
     * @return bool
     */
    public function getParse()
    {
        return $this->container['parse'];
    }

    /**
     * Sets parse
     *
     * @param bool $parse DEPRECATED. Will be ignored.
     *
     * @return $this
     */
    public function setParse($parse)
    {
        $this->container['parse'] = $parse;

        return $this;
    }

    /**
     * Gets parse_strategy
     *
     * @return string
     */
    public function getParseStrategy()
    {
        return $this->container['parse_strategy'];
    }

    /**
     * Sets parse_strategy
     *
     * @param string $parse_strategy How to parse the document.
     *
     * @return $this
     */
    public function setParseStrategy($parse_strategy)
    {
        $allowedValues = $this->getParseStrategyAllowableValues();
        if (!is_null($parse_strategy) && !in_array($parse_strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'parse_strategy', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['parse_strategy'] = $parse_strategy;

        return $this;
    }

    /**
     * Gets document
     *
     * @return string
     */
    public function getDocument()
    {
        return $this->container['document'];
    }

    /**
     * Sets document
     *
     * @param string $document The base64 encoded version of the document.
     *
     * @return $this
     */
    public function setDocument($document)
    {

        if ((mb_strlen($document) < 5)) {
            throw new \InvalidArgumentException('invalid length for $document when calling RawDocumentData., must be bigger than or equal to 5.');
        }

        $this->container['document'] = $document;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


