<?php
/**
 * AdditionalTaxIdentifiersApi
 * PHP version 5
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Deegitalbe\LaravelTrustupIoStorecove\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Deegitalbe\LaravelTrustupIoStorecove\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * AdditionalTaxIdentifiersApi Class Doc Comment
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AdditionalTaxIdentifiersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAdditionalTaxIdentifier
     *
     * Create a new AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity for which to create the AdditionalTaxIdentifier (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierCreate  $additional_tax_identifier  AdditionalTaxIdentifier to create (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function createAdditionalTaxIdentifier($legal_entity_id, $additional_tax_identifier)
    {
        [$response] = $this->createAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $additional_tax_identifier);

        return $response;
    }

    /**
     * Operation createAdditionalTaxIdentifierWithHttpInfo
     *
     * Create a new AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity for which to create the AdditionalTaxIdentifier (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierCreate  $additional_tax_identifier  AdditionalTaxIdentifier to create (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function createAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $additional_tax_identifier)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->createAdditionalTaxIdentifierRequest($legal_entity_id, $additional_tax_identifier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\ErrorModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createAdditionalTaxIdentifierAsync
     *
     * Create a new AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity for which to create the AdditionalTaxIdentifier (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierCreate  $additional_tax_identifier  AdditionalTaxIdentifier to create (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function createAdditionalTaxIdentifierAsync($legal_entity_id, $additional_tax_identifier)
    {
        return $this->createAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $additional_tax_identifier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAdditionalTaxIdentifierAsyncWithHttpInfo
     *
     * Create a new AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity for which to create the AdditionalTaxIdentifier (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierCreate  $additional_tax_identifier  AdditionalTaxIdentifier to create (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function createAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $additional_tax_identifier)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->createAdditionalTaxIdentifierRequest($legal_entity_id, $additional_tax_identifier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAdditionalTaxIdentifier'
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity for which to create the AdditionalTaxIdentifier (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierCreate  $additional_tax_identifier  AdditionalTaxIdentifier to create (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function createAdditionalTaxIdentifierRequest($legal_entity_id, $additional_tax_identifier)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null || (is_array($legal_entity_id) && count($legal_entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling createAdditionalTaxIdentifier'
            );
        }
        // verify the required parameter 'additional_tax_identifier' is set
        if ($additional_tax_identifier === null || (is_array($additional_tax_identifier) && count($additional_tax_identifier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $additional_tax_identifier when calling createAdditionalTaxIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/additional_tax_identifiers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{'.'legal_entity_id'.'}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($additional_tax_identifier)) {
            $_tempBody = $additional_tax_identifier;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteAdditionalTaxIdentifier
     *
     * Delete AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return void
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function deleteAdditionalTaxIdentifier($legal_entity_id, $id)
    {
        $this->deleteAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id);
    }

    /**
     * Operation deleteAdditionalTaxIdentifierWithHttpInfo
     *
     * Delete AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function deleteAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id)
    {
        $returnType = '';
        $request = $this->deleteAdditionalTaxIdentifierRequest($legal_entity_id, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAdditionalTaxIdentifierAsync
     *
     * Delete AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function deleteAdditionalTaxIdentifierAsync($legal_entity_id, $id)
    {
        return $this->deleteAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAdditionalTaxIdentifierAsyncWithHttpInfo
     *
     * Delete AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function deleteAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id)
    {
        $returnType = '';
        $request = $this->deleteAdditionalTaxIdentifierRequest($legal_entity_id, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAdditionalTaxIdentifier'
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function deleteAdditionalTaxIdentifierRequest($legal_entity_id, $id)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null || (is_array($legal_entity_id) && count($legal_entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling deleteAdditionalTaxIdentifier'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteAdditionalTaxIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{'.'legal_entity_id'.'}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{'.'id'.'}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'DELETE',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAdditionalTaxIdentifier
     *
     * Get AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function getAdditionalTaxIdentifier($legal_entity_id, $id)
    {
        [$response] = $this->getAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id);

        return $response;
    }

    /**
     * Operation getAdditionalTaxIdentifierWithHttpInfo
     *
     * Get AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function getAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->getAdditionalTaxIdentifierRequest($legal_entity_id, $id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAdditionalTaxIdentifierAsync
     *
     * Get AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function getAdditionalTaxIdentifierAsync($legal_entity_id, $id)
    {
        return $this->getAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAdditionalTaxIdentifierAsyncWithHttpInfo
     *
     * Get AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function getAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->getAdditionalTaxIdentifierRequest($legal_entity_id, $id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAdditionalTaxIdentifier'
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function getAdditionalTaxIdentifierRequest($legal_entity_id, $id)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null || (is_array($legal_entity_id) && count($legal_entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling getAdditionalTaxIdentifier'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAdditionalTaxIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{'.'legal_entity_id'.'}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{'.'id'.'}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAdditionalTaxIdentifier
     *
     * Update AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier to be updated (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierUpdate  $additional_tax_identifier  AdditionalTaxIdentifier to update (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function updateAdditionalTaxIdentifier($legal_entity_id, $id, $additional_tax_identifier)
    {
        [$response] = $this->updateAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id, $additional_tax_identifier);

        return $response;
    }

    /**
     * Operation updateAdditionalTaxIdentifierWithHttpInfo
     *
     * Update AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier to be updated (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierUpdate  $additional_tax_identifier  AdditionalTaxIdentifier to update (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function updateAdditionalTaxIdentifierWithHttpInfo($legal_entity_id, $id, $additional_tax_identifier)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->updateAdditionalTaxIdentifierRequest($legal_entity_id, $id, $additional_tax_identifier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateAdditionalTaxIdentifierAsync
     *
     * Update AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier to be updated (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierUpdate  $additional_tax_identifier  AdditionalTaxIdentifier to update (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function updateAdditionalTaxIdentifierAsync($legal_entity_id, $id, $additional_tax_identifier)
    {
        return $this->updateAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id, $additional_tax_identifier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAdditionalTaxIdentifierAsyncWithHttpInfo
     *
     * Update AdditionalTaxIdentifier
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier to be updated (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierUpdate  $additional_tax_identifier  AdditionalTaxIdentifier to update (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function updateAdditionalTaxIdentifierAsyncWithHttpInfo($legal_entity_id, $id, $additional_tax_identifier)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifier';
        $request = $this->updateAdditionalTaxIdentifierRequest($legal_entity_id, $id, $additional_tax_identifier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAdditionalTaxIdentifier'
     *
     * @param  int  $legal_entity_id  The id of the LegalEntity the AdditionalTaxIdentifier belongs to (required)
     * @param  int  $id  The id of the AdditionalTaxIdentifier to be updated (required)
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\AdditionalTaxIdentifierUpdate  $additional_tax_identifier  AdditionalTaxIdentifier to update (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function updateAdditionalTaxIdentifierRequest($legal_entity_id, $id, $additional_tax_identifier)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null || (is_array($legal_entity_id) && count($legal_entity_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling updateAdditionalTaxIdentifier'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateAdditionalTaxIdentifier'
            );
        }
        // verify the required parameter 'additional_tax_identifier' is set
        if ($additional_tax_identifier === null || (is_array($additional_tax_identifier) && count($additional_tax_identifier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $additional_tax_identifier when calling updateAdditionalTaxIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/additional_tax_identifiers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{'.'legal_entity_id'.'}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{'.'id'.'}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($additional_tax_identifier)) {
            $_tempBody = $additional_tax_identifier;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'PATCH',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @return array of http client options
     *
     * @throws \RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (! $options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: '.$this->config->getDebugFile());
            }
        }

        return $options;
    }
}
