<?php
/**
 * InvoiceSubmissionsApi
 * PHP version 5
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Deegitalbe\LaravelTrustupIoStorecove\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Deegitalbe\LaravelTrustupIoStorecove\ApiException;
use Deegitalbe\LaravelTrustupIoStorecove\Configuration;
use Deegitalbe\LaravelTrustupIoStorecove\HeaderSelector;
use Deegitalbe\LaravelTrustupIoStorecove\ObjectSerializer;

/**
 * InvoiceSubmissionsApi Class Doc Comment
 *
 * @category Class
 *
 * @author   Swagger Codegen team
 *
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceSubmissionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createInvoiceSubmission
     *
     * DEPRECATED. Submit a new invoice
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmission  $invoice_submission  Invoice to submit (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionResult
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function createInvoiceSubmission($invoice_submission)
    {
        [$response] = $this->createInvoiceSubmissionWithHttpInfo($invoice_submission);

        return $response;
    }

    /**
     * Operation createInvoiceSubmissionWithHttpInfo
     *
     * DEPRECATED. Submit a new invoice
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmission  $invoice_submission  Invoice to submit (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionResult, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function createInvoiceSubmissionWithHttpInfo($invoice_submission)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionResult';
        $request = $this->createInvoiceSubmissionRequest($invoice_submission);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\ErrorModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createInvoiceSubmissionAsync
     *
     * DEPRECATED. Submit a new invoice
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmission  $invoice_submission  Invoice to submit (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function createInvoiceSubmissionAsync($invoice_submission)
    {
        return $this->createInvoiceSubmissionAsyncWithHttpInfo($invoice_submission)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createInvoiceSubmissionAsyncWithHttpInfo
     *
     * DEPRECATED. Submit a new invoice
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmission  $invoice_submission  Invoice to submit (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function createInvoiceSubmissionAsyncWithHttpInfo($invoice_submission)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionResult';
        $request = $this->createInvoiceSubmissionRequest($invoice_submission);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createInvoiceSubmission'
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmission  $invoice_submission  Invoice to submit (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function createInvoiceSubmissionRequest($invoice_submission)
    {
        // verify the required parameter 'invoice_submission' is set
        if ($invoice_submission === null || (is_array($invoice_submission) && count($invoice_submission) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_submission when calling createInvoiceSubmission'
            );
        }

        $resourcePath = '/invoice_submissions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // body params
        $_tempBody = null;
        if (isset($invoice_submission)) {
            $_tempBody = $invoice_submission;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation preflightInvoiceRecipient
     *
     * DEPRECATED. Preflight an invoice recipient
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceRecipientPreflight  $invoice_recipient_preflight  The invoice recipient to preflight (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\PreflightInvoiceRecipientResult
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function preflightInvoiceRecipient($invoice_recipient_preflight)
    {
        [$response] = $this->preflightInvoiceRecipientWithHttpInfo($invoice_recipient_preflight);

        return $response;
    }

    /**
     * Operation preflightInvoiceRecipientWithHttpInfo
     *
     * DEPRECATED. Preflight an invoice recipient
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceRecipientPreflight  $invoice_recipient_preflight  The invoice recipient to preflight (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\PreflightInvoiceRecipientResult, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function preflightInvoiceRecipientWithHttpInfo($invoice_recipient_preflight)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\PreflightInvoiceRecipientResult';
        $request = $this->preflightInvoiceRecipientRequest($invoice_recipient_preflight);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\ErrorModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\PreflightInvoiceRecipientResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation preflightInvoiceRecipientAsync
     *
     * DEPRECATED. Preflight an invoice recipient
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceRecipientPreflight  $invoice_recipient_preflight  The invoice recipient to preflight (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function preflightInvoiceRecipientAsync($invoice_recipient_preflight)
    {
        return $this->preflightInvoiceRecipientAsyncWithHttpInfo($invoice_recipient_preflight)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation preflightInvoiceRecipientAsyncWithHttpInfo
     *
     * DEPRECATED. Preflight an invoice recipient
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceRecipientPreflight  $invoice_recipient_preflight  The invoice recipient to preflight (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function preflightInvoiceRecipientAsyncWithHttpInfo($invoice_recipient_preflight)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\PreflightInvoiceRecipientResult';
        $request = $this->preflightInvoiceRecipientRequest($invoice_recipient_preflight);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'preflightInvoiceRecipient'
     *
     * @param  \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceRecipientPreflight  $invoice_recipient_preflight  The invoice recipient to preflight (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function preflightInvoiceRecipientRequest($invoice_recipient_preflight)
    {
        // verify the required parameter 'invoice_recipient_preflight' is set
        if ($invoice_recipient_preflight === null || (is_array($invoice_recipient_preflight) && count($invoice_recipient_preflight) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_recipient_preflight when calling preflightInvoiceRecipient'
            );
        }

        $resourcePath = '/invoice_submissions/preflight';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // body params
        $_tempBody = null;
        if (isset($invoice_recipient_preflight)) {
            $_tempBody = $invoice_recipient_preflight;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'POST',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation showInvoiceSubmissionEvidence
     *
     * DEPRECATED. Get InvoiceSubmission Evidence
     *
     * @param  string  $guid  InvoiceSubmission GUID (required)
     * @return \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionEvidence
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function showInvoiceSubmissionEvidence($guid)
    {
        [$response] = $this->showInvoiceSubmissionEvidenceWithHttpInfo($guid);

        return $response;
    }

    /**
     * Operation showInvoiceSubmissionEvidenceWithHttpInfo
     *
     * DEPRECATED. Get InvoiceSubmission Evidence
     *
     * @param  string  $guid  InvoiceSubmission GUID (required)
     * @return array of \Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionEvidence, HTTP status code, HTTP response headers (array of strings)
     *
     * @throws \Deegitalbe\LaravelTrustupIoStorecove\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function showInvoiceSubmissionEvidenceWithHttpInfo($guid)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionEvidence';
        $request = $this->showInvoiceSubmissionEvidenceRequest($guid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionEvidence',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation showInvoiceSubmissionEvidenceAsync
     *
     * DEPRECATED. Get InvoiceSubmission Evidence
     *
     * @param  string  $guid  InvoiceSubmission GUID (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function showInvoiceSubmissionEvidenceAsync($guid)
    {
        return $this->showInvoiceSubmissionEvidenceAsyncWithHttpInfo($guid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation showInvoiceSubmissionEvidenceAsyncWithHttpInfo
     *
     * DEPRECATED. Get InvoiceSubmission Evidence
     *
     * @param  string  $guid  InvoiceSubmission GUID (required)
     * @return \GuzzleHttp\Promise\PromiseInterface
     *
     * @throws \InvalidArgumentException
     */
    public function showInvoiceSubmissionEvidenceAsyncWithHttpInfo($guid)
    {
        $returnType = '\Deegitalbe\LaravelTrustupIoStorecove\Model\InvoiceSubmissionEvidence';
        $request = $this->showInvoiceSubmissionEvidenceRequest($guid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'showInvoiceSubmissionEvidence'
     *
     * @param  string  $guid  InvoiceSubmission GUID (required)
     * @return \GuzzleHttp\Psr7\Request
     *
     * @throws \InvalidArgumentException
     */
    protected function showInvoiceSubmissionEvidenceRequest($guid)
    {
        // verify the required parameter 'guid' is set
        if ($guid === null || (is_array($guid) && count($guid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $guid when calling showInvoiceSubmissionEvidence'
            );
        }

        $resourcePath = '/invoice_submissions/{guid}/evidence';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // path params
        if ($guid !== null) {
            $resourcePath = str_replace(
                '{'.'guid'.'}',
                ObjectSerializer::toPathValue($guid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue,
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);

        return new Request(
            'GET',
            $this->config->getHost().$resourcePath.($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @return array of http client options
     *
     * @throws \RuntimeException on file opening failure
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (! $options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: '.$this->config->getDebugFile());
            }
        }

        return $options;
    }
}
